### ISSUE TITLE
WF Rights 

### ISSUE THREAD

**Issue by behramcelen** [okulbilisim/ojs#1036]
Editor in Chief and JM has all rights.

section editor:
- [x] close thread 
- [x] reject & close thread
- [x] close step & reject article
- [x] new thread

Prof, copy ve layout:
- [X] close thread 
- [ ] ~~new thread (author, editor and/or section editor)~~

author:
- [x] close thread 
- [x] reject & close thread
- [x] withdraw
- [ ] ~~new thread (editor and section editor)~~

rewier:
- [x] close thread
- [x] reject & close thread
- [ ] ~~new thread (editor and section editor)~~

**Comment by beyzakokcan** [comment]
key user:
close thread
reject & close thread
new thread 

user: 
close thread

if you create this two new roles, then journal manager selects them and assign a user for these roles

**Comment by beyzakokcan** [comment]
reopen please
