### ISSUE TITLE
Contacts

### ISSUE THREAD

**Issue by beyzakokcan** [okulbilisim/ojs#1062]
It will be much simpler. 
First title and contact type will be removed. 
There will be 3 contact types as default.These are;
Primary Contact (Email, phone) -editor
Secretary (email, phone)
Technical Contact

If journal manager wants to add a new contact, there will be just these fields;
Contact type* (text, string )
Name*,
email*,
phone,
instution,
address

**Comment by behramcelen** [comment]
`There will be 3 contact types as default`
contact type have all crud processes you can design easily how you want.
