### ISSUE TITLE
WF Rights 

### ISSUE THREAD

**Issue by beyzakokcan** [okulbilisim/ojs#1090]
There is a related issue: https://github.com/okulbilisim/ojs/issues/1036

But some of them does not work. (some are crossed?)

Author should open a new thread,  (editor and section editor)
Prof, copy ve layout: new thread  (author, editor and/or section editor)
reviewer: new thread  (editor and section editor)

Also section editor should edit the article as editor.

**Comment by hmert** [comment]
Discussed with @beyzakokcan and It's OK for this moment.
