### ISSUE TITLE
Mandotory fields for article file should be revised

### ISSUE THREAD

**Issue by beyzakokcan** [okulbilisim/ojs#1091]
We talked about it but we still get warning messages. 

You can check: https://jira.ulakbim.gov.tr/browse/DER-1139?jql=text%20~%20%22zorunlu%20alan%22

**Comment by beyzakokcan** [comment]
For example, editor cannot edit the article because article published date is mandatory but article is still in review

**Comment by behramcelen** [comment]
revised and added asterisk sign to required label texts with https://github.com/okulbilisim/ojs/commit/e60bb3f1ad09c8de5272d805f35c69bcd1d6530a

**Comment by behramcelen** [comment]
![image](https://cloud.githubusercontent.com/assets/4572080/10481877/9242e182-727c-11e5-9481-d523649627ad.png)
