### ISSUE TITLE
Article Status

### ISSUE THREAD

**Issue by beyzakokcan** [okulbilisim/ojs#1093]
There should be article status for each roles so that users can follow their works. We talked about it and you can check: https://jira.ulakbim.gov.tr/browse/DER-1141
For exampe,
I logged in as a reviewer and finished the review, but article is still on the review page. 
If there is much more article how can I know which ones are reviewed which ones are waiting. (Or due date is passed?)

**Comment by hmert** [comment]
fixed with #1166
