### ISSUE TITLE
Rich Text Editor buttons revise

### ISSUE THREAD

**Issue by behramcelen** [okulbilisim/ojs#1104]
![dergi duzenle ojs](https://cloud.githubusercontent.com/assets/4572080/10220166/cf9f0f44-684d-11e5-8927-baee9ef8f399.png)

**Comment by hmert** [comment]
![image](https://cloud.githubusercontent.com/assets/182906/10360538/1b443ecc-6daa-11e5-8334-869e35e1e375.png)
