### ISSUE TITLE
If user registered to one journal, it can direct to dashboard

### ISSUE THREAD

**Issue by beyzakokcan** [okulbilisim/ojs#1108]
If user registered to one journal, user may not need to say "switch", dashboard can be open automatically.

(If user not registered to any journal then, a warning can be shown on dashboard saying " click on the explore and click on the journal you want to register and submit a paper"  (tour ) )

**Comment by behramcelen** [comment]
if want to see his/her statics about own articles can not reach own dashboard because of redirect.
