### ISSUE TITLE
uploading a file, at the first attempt, it gives error

### ISSUE THREAD

**Issue by beyzakokcan** [okulbilisim/ojs#1109]
If user uploads a file at the first attempt, it gives error "whitelist error". 
Not related to whitelist, because in the second try, it uploads the file.

**Comment by behramcelen** [comment]
can you support a URI. and i tried on article submission start and article file uploads but i can't see an error. can you tell which type of file you are uploading

**Comment by beyzakokcan** [comment]
I have uploaded doc. and pdf.

**Comment by beyzakokcan** [comment]
The bug seems fixed maybe it was because of cache too.

**Comment by behramcelen** [comment]
ok i am closing then
