### ISSUE TITLE
Add author, article files not working

### ISSUE THREAD

**Issue by beyzakokcan** [okulbilisim/ojs#1110]
Butons like add author, add article files... etc do not work

**Comment by behramcelen** [comment]
Related error : `Uncaught Error: Syntax error, unrecognized expression: <div class="submission-subform">
        <div class="form-group"><label class="control-label required" for="ojs_article_submission_articleAuthors_1_author_firstName">First name</label><input type="text"     id="ojs_article_submission_articleAuthors_1_author_firstName" name="ojs_article_submission[articleAuthors][1][author][firstName]" required="required" maxlength="255"        maxlength="255" class="form-control" ></div>
        <div class="form-group"><label class="control-label required" for="ojs_article_su ...`
