### ISSUE TITLE
after registration no mail or approve

### ISSUE THREAD

**Issue by beyzakokcan** [okulbilisim/ojs#1112]
- [ ] Users register but they do not get a notification that registration is successful and do not get a welcome mail

**Comment by beyzakokcan** [comment]
On dashboard, it gives the notifications but after registration, it directs to home. So if you send a mail and direct to dashboard, it is ok. 

Also if user is not registered to any journal, a warning can be added; " you can explore journals on the explore and register on the journal page "

**Comment by hmert** [comment]
#1031
