### ISSUE TITLE
Profile Update

### ISSUE THREAD

**Issue by hmert** [okulbilisim/ojs#1117]
![image](https://cloud.githubusercontent.com/assets/182906/10333370/0b93f3aa-6cec-11e5-98fa-115b87e6e486.png)

- [x] bio -> about
- [x] country / city
- [x] website -> url
- [x] email

We should update some of fields with like above

**Comment by behramcelen** [comment]
![image](https://cloud.githubusercontent.com/assets/4572080/10450449/079f8e38-71a3-11e5-9256-36951f236541.png)
