### ISSUE TITLE
Country city selection encoding problem

### ISSUE THREAD

**Issue by behramcelen** [okulbilisim/ojs#1157]
![image](https://cloud.githubusercontent.com/assets/4572080/10364929/1215e260-6dc8-11e5-8363-ce746ffa7990.png)

**Comment by behramcelen** [comment]
Problem source from here https://github.com/okulbilisim/LocationBundle/blob/master/Resources/data/location.sql#L1415

**Comment by behramcelen** [comment]
Related https://github.com/tayyabhussain/Countries-and-Cities-Database

**Comment by hmert** [comment]
I committed a new branch which has more cities.  https://github.com/okulbilisim/LocationBundle/tree/unitednations

**Comment by hmert** [comment]
https://github.com/okulbilisim/ojs/commit/a1747e46dcf554af1a57452ac83bbc3829c64ab0
