### ISSUE TITLE
"Is anonymous" field shouldn't be a radio input

### ISSUE THREAD

**Issue by utkuaydin** [okulbilisim/ojs#1182]
It is impossible to deselect "is anonymous" field now in Article form.

![Screenshot](https://cloud.githubusercontent.com/assets/1607716/10393388/408e7a5a-6e98-11e5-93cb-d8b154ffbd84.png)

**Comment by behramcelen** [comment]
Duplicate issue with https://github.com/okulbilisim/ojs/issues/1137 closes
