### ISSUE TITLE
Feedback form not works

### ISSUE THREAD

**Issue by behramcelen** [okulbilisim/ojs#1187]
![image](https://cloud.githubusercontent.com/assets/4572080/10395950/5ea5a94a-6ea8-11e5-986c-7b504c84b0dc.png)

**Comment by hmert** [comment]
Please update it. `composer update`

**Comment by behramcelen** [comment]
i updated composer but not works.

**Comment by behramcelen** [comment]
tested and works. but can be shown an success message after feedback send event.
