### ISSUE TITLE
search results type UX

### ISSUE THREAD

**Issue by beyzakokcan** [okulbilisim/ojs#1241]
Hüseyin gets the point

**Comment by beyzakokcan** [comment]
highlighted words

**Comment by beyzakokcan** [comment]
filters: subjects, publishers, languages, indexes..

**Comment by hmert** [comment]
![image](https://cloud.githubusercontent.com/assets/182906/10710909/e1c1a226-7a73-11e5-94d2-5e316bc77ce5.png)

**Comment by hmert** [comment]
@utkuaydin could you add if it is enabled to find  "publishers, languages, indexes" filters to the search page?
