### ISSUE TITLE
maybe later: as forwarding to next step, files from the previous step..

### ISSUE THREAD

**Issue by beyzakokcan** [okulbilisim/ojs#1245]
can automatically added to the new dialog appearing as a forwarding message. But files can be checked so managers can choose one or more. 
I am very sure editors will request the same :)

**Comment by beyzakokcan** [comment]
There will not so much files anyway on the each step. For example reviewers do not upload a file usually, they just fill the review form. Or any similar solutions can be acceptable, if it includes forwarding the related files to the next step automatically.

**Comment by hmert** [comment]
we should provide a file version tracker instead of doing this
