### ISSUE TITLE
Dashboard

### ISSUE THREAD

**Issue by hmert** [okulbilisim/ojs#1272]
personalized article counts on pie chart

**Comment by hmert** [comment]
![image](https://cloud.githubusercontent.com/assets/182906/10938261/5a67d08e-8301-11e5-9618-a33f3e4ec8ba.png)

**Comment by behramcelen** [comment]
![image](https://cloud.githubusercontent.com/assets/4572080/10952951/df8c0f4a-834d-11e5-9ff0-9a684a123676.png)
