### ISSUE TITLE
Exception on journal application 

### ISSUE THREAD

**Issue by behramcelen** [okulbilisim/ojs#1282]
if i create an new publisher on journal application
![image](https://cloud.githubusercontent.com/assets/4572080/11049550/c07f1d74-8747-11e5-985b-e2e8429f5766.png)

**Comment by behramcelen** [comment]
i did not get error on live system. I will re-try on my local system

**Comment by behramcelen** [comment]
I did not get error on live but publisher type is not exists
![image](https://cloud.githubusercontent.com/assets/4572080/11050880/cff693f8-8752-11e5-98d9-2984860b6997.png)

**Comment by behramcelen** [comment]
ping @utkuaydin

**Comment by utkuaydin** [comment]
55f80ab fixes the null `publisherType` problem.
