### ISSUE TITLE
Author cannot view his article in workflow on his dashboard

### ISSUE THREAD

**Issue by beyzakokcan** [okulbilisim/ojs#1313]
Author: beyzabas
First article.
It gives error: Call to a member function hasUser() on a non-object.

**Comment by behramcelen** [comment]
![image](https://cloud.githubusercontent.com/assets/4572080/11187544/87c08b4c-8c8f-11e5-91f3-0ad3916f00d0.png)
![image](https://cloud.githubusercontent.com/assets/4572080/11187575/a3ec2402-8c8f-11e5-97f7-c9efda61fdd6.png)

**Comment by behramcelen** [comment]
fixed with wf bundle
