### ISSUE TITLE
instution appear twice on submission

### ISSUE THREAD

**Issue by beyzakokcan** [okulbilisim/ojs#1330]
When you click on add authors then "instutions" appear twice.
![screen shot 2015-11-19 at 17 42 04](https://cloud.githubusercontent.com/assets/2804889/11275161/fd44c624-8ee4-11e5-9e74-3168edc879ed.png)

**Comment by behramcelen** [comment]
fixed with https://github.com/okulbilisim/ojs/commit/b26fa23162ac3777617060232ac2300537b50e3f
