### ISSUE TITLE
"People" should include subject/interest filter

### ISSUE THREAD

**Issue by beyzakokcan** [okulbilisim/ojs#1342]
But not as a list. Because people can write so many different interest. So this filter can only be a search bar. And i think that feature can be really helpful especially for Finding the reviewers according to their review interest.

**Comment by hmert** [comment]
tag cloud :+1:

**Comment by behramcelen** [comment]
subject filter already exists
![image](https://cloud.githubusercontent.com/assets/4572080/11426113/56051340-9462-11e5-8dbc-ae9a3b4cda12.png)
I am closing issue now. Interest will revise on other issue
