### ISSUE TITLE
Bug: quickaction

### ISSUE THREAD

**Issue by beyzakokcan** [okulbilisim/ojs#1345]
I logged in as a journal manager (filizmenguc,123456)
When I submit an article, quick action showed me dashboard, articles in progress and articles in past workflow. But if you click on articles in progress and past, it gives error; 
An exception has been thrown during the rendering of a template ("Entity of type 'Ojs\JournalBundle\Entity\Article' for IDs id(38685) was not found") in WorkflowBundle:WorkFlow:flows.html.twig at line 28.

**Comment by behramcelen** [comment]
I can not re-produce scenario with user filizmenguc:123456 probably it can be fixed

**Comment by behramcelen** [comment]
tested and works correctly
