### ISSUE TITLE
Search Not show it at the top as the most related item.

### ISSUE THREAD

**Issue by beyzakokcan** [okulbilisim/ojs#1352]
I searched Ömer Keleş. But it did not show it at the first page.  Then I searched it on the advanced search; it did not show it at the top. as the most related answer, it should be at the top.
![screen shot 2015-11-25 at 12 20 05](https://cloud.githubusercontent.com/assets/2804889/11394643/15ceb1d0-936f-11e5-994d-ff1bc8d2325d.png)

**Comment by behramcelen** [comment]
your searched author firstname field is `Ö.`
![image](https://cloud.githubusercontent.com/assets/4572080/11501083/1ed5710e-983a-11e5-975b-95391a64acd3.png)
So this result is correctly works http://beta.dergipark.gov.tr/search?q=%28%28%C3%B6%5Bauthor.firstName%5D%29+AND+kele%C5%9F%5Bauthor.lastName%5D%29&type=advanced&section=author
