### ISSUE TITLE
admin changes passw but how user know the new passw?

### ISSUE THREAD

**Issue by beyzakokcan** [okulbilisim/ojs#1353]
for example, admin changes the user passw, then how will admin inform the user that passw has been changed, and the new passw is...? OJS uses check boxes. first ones; "assing a random passw " "make the passw this .." and then another chekbox is "make the user change passw at the first log in" and the other "send a welcome mail to the user including the new passw"..

**Comment by behramcelen** [comment]
We have this event type https://github.com/okulbilisim/ojs/blob/master/src/Ojs/AdminBundle/Events/AdminEvents.php#L7
user will be notified by mail.
