### ISSUE TITLE
bug: updating journal !!

### ISSUE THREAD

**Issue by beyzakokcan** [okulbilisim/ojs#1367]
http://ege-tarimsal-arastirma-enstitusu.beta.dergipark.gov.tr/admin/journal/120/update

![screen shot 2015-12-17 at 13 52 16](https://cloud.githubusercontent.com/assets/2804889/11869113/7ece828e-a4c5-11e5-8c5b-4e3d99290405.png)

**Comment by behramcelen** [comment]
probably this issue fixed can you re-test and if there is an bug dump the scenario below. ping @beyzakokcan

**Comment by behramcelen** [comment]
i am closing this issue according to my tests. if error resumes anyone can re-open.
