### ISSUE TITLE
Delete Feature

### ISSUE THREAD

**Issue by hmert** [okulbilisim/ojs#1372]
- [x] Journal
- [x] Issue
- [x] Article

**Comment by beyzakokcan** [comment]
enough

**Comment by utkuaydin** [comment]
It would be great if you could test these to see if they are working as intended while we are in the beta stage.

**Comment by beyzakokcan** [comment]
of course. I always test :)

**Comment by beyzakokcan** [comment]
user and journal are not our priority right now. You can close the issue after testing. We can go back to user and journal later.

**Comment by utkuaydin** [comment]
Journal is already done. I'll leave user deletion for later.

**Comment by beyzakokcan** [comment]
Great. Thank you.
