### ISSUE TITLE
journal settings update bug 

### ISSUE THREAD

**Issue by beyzakokcan** [okulbilisim/ojs#1384]
I can update but it does not show what is updated.

https://drive.google.com/file/d/0B7yJMr_wSCAYRHZJeWY0cy1aUFU/view

**Comment by behramcelen** [comment]
Problem detected and fixed permanently with this commit 
https://github.com/okulbilisim/ojs/commit/f5f2093a1355591a9f108ec4794d366d6fc7c4b9
