### ISSUE TITLE
Problem about the theme

### ISSUE THREAD

**Issue by beyzakokcan** [okulbilisim/ojs#1385]
header, blog posts and pages are not shown if I choose a different theme for exampe (super hero)

**Comment by beyzakokcan** [comment]
https://drive.google.com/file/d/0B7yJMr_wSCAYdlE5N3pZYTNKVkk/view

**Comment by behramcelen** [comment]
problem source is here https://github.com/okulbilisim/ojs/blob/master/src/Ojs/JournalBundle/Entity/JournalRepository.php#L25.
I will not get journal from journal_service for only journal settings page
