### ISSUE TITLE
yml parse error

### ISSUE THREAD

**Issue by jixaCo** [okulbilisim/ojs#294]
Hi 
I want to install ojs but when I run "php app/console doctrine:database:create" , this error coms :
[Symfony\Component\Config\Exception\FileLoaderLoadException]                                                                                                       
  Unable to parse at line 12 (near " type: memory") in /srv/http/ojs-1/app/config/swift.yml (which is being imported from "/srv/http/ojs-1/app/config/config.yml").

**Comment by aybarscengaver** [comment]
This option have a extra tab, i will fix it in day.

**Comment by hasantayyar** [comment]
This should be fixed https://github.com/okulbilisim/ojs/commit/dd3bb8c7443808e1f7982d99f0d38fd8094c5fba 

Please pull latest version.

**Comment by hmert** [comment]
@jixaCo have you tested it? is it fixed now?

**Comment by jixaCo** [comment]
tnx
