### ISSUE TITLE
ContextErrorException in LoggingMemcache.php

### ISSUE THREAD

**Issue by jixaCo** [okulbilisim/ojs#297]
after installing this error apears :

Runtime Notice: Declaration of Lsw\MemcacheBundle\Cache\LoggingMemcache::get() should be compatible with Memcached::get($key, $cache_cb = NULL, &$cas_token = NULL, &$udf_flags = NULL)

**Comment by aybarscengaver** [comment]
what's your memcache version ?

**Comment by jixaCo** [comment]
2.2.0

**Comment by jixaCo** [comment]
memcached : 2.2.0
memcache : 3.0.8

**Comment by hmert** [comment]
@jixaCo we removed this buggy memcache lib. So your problem should be fixed now? Please, confirm that?

**Comment by jixaCo** [comment]
another Error : 
  
[Symfony\Component\Config\Exception\FileLoaderLoadException]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
  There is no extension able to load the configuration for "lsw_memcache" (in /../app/config/parameters.yml). Looked for namespace "lsw_memcache", found "framework", "security", "twig", "monolog", "swiftmailer", "assetic", "doctrine", "sensio_framework_extra", "fos_rest", "jms_serializer", "nelmio_api_doc", "stof_doctrine_extensions", "oneup_uploader", "liip_imagine", "knp_paginator", "doctrine_mongodb", "fos_elastica", "braincrafted_bootstrap", "ojs_oai", "jms_job_queue", "jms_di_extra", "jms_aop", "ojs_report", "okulbilisim_feedback", "okulbilisim_message", "ojs_installer", "okulbilisim_cms", "unifik_database_config", "ojs_notifier", "web_profiler", "sensio_distribution", "h4cc_alice_fixtures" in /.../app/config/parameters.yml (which is being imported from "/.../app/config/config.yml").

**Comment by hmert** [comment]
in parameters.yml you should delete lines about `lsw_memcache`

**Comment by jixaCo** [comment]
thanks , It works now

**Comment by hmert** [comment]
👏
