### ISSUE TITLE
User profile for custom fields

### ISSUE THREAD

**Issue by hmert** [okulbilisim/ojs#300]
A user may have in his/her profile custom fields. URL or string.

```
title: String (128)
value: String (1024) 
url: String (1024)
is_url : boolen
```

![screen shot 2015-02-01 at 1 14 31 pm](https://cloud.githubusercontent.com/assets/182906/5991893/768d0188-aa14-11e4-8272-a9a287ef77cb.png)

![profile](https://cloud.githubusercontent.com/assets/182906/5991895/8b7842b0-aa14-11e4-9c59-7ab8e0c4c67c.png)

- [ ] Edit / Add Custom Field for profile (admin page)
- [ ] Show Custom Fields
- [ ] REST API read/write

**Comment by ismailbaskin** [comment]
admin mi ekleyecek custom fieldleri?

**Comment by ismailbaskin** [comment]
bunu ID'de de yapak
