### ISSUE TITLE
Data fixture error

### ISSUE THREAD

**Issue by jixaCo** [okulbilisim/ojs#301]
when I run "php app/console h4cc_alice_fixtures:load:set"
                                                 
  [Elastica\Exception\Connection\HttpException]  
  Couldn't connect to host, Elasticsearch down?

**Comment by hmert** [comment]
is ElasticSearch up? (installed)

**Comment by jixaCo** [comment]
yes it is installed

**Comment by hmert** [comment]
Have you tried `netstat -ant|grep LISTEN|grep 9200` this and what was the output

**Comment by jixaCo** [comment]
yes I tried that and the output is nothing !

**Comment by hmert** [comment]
it means that your ElasticSearch instance isn't running. Try to start it. 
http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/setup.html

**Comment by jixaCo** [comment]
Thank You
