### ISSUE TITLE
Thesaurus integration

### ISSUE THREAD

**Issue by hmert** [okulbilisim/ojs#335]

**Comment by aybarscengaver** [comment]
http://www.quora.com/Is-there-an-online-synonym-API

http://words.bighugelabs.com/api.php

http://thesaurus.altervista.org/

http://www.programmableweb.com/api/thesaurus

**Comment by hasantayyar** [comment]
We will integrate more services https://github.com/okulbilisim/thesaurus-manager/blob/master/app/commands/ThesaurusSuggestions.php 

Bbut the main objective of this thesaurus project is to create a custom thesaurus manager companies/institutions.

**Comment by behramcelen** [comment]
Related : https://github.com/okulbilisim/thesaurus-manager/
