### ISSUE TITLE
Log Manager

### ISSUE THREAD

**Issue by hmert** [okulbilisim/ojs#348]
- [x] All user activity
    * Audit log (login, logout, password change)
    * Workflow update log
    * Proxy actions log 
    * Article submission
- [x] view the log by ROLE, USER and JOURNAL

**Comment by hmert** [comment]
is this issue finished? @aybarscengaver @behramcelen

**Comment by behramcelen** [comment]
user login, logout action log
proxy create, drop action log
article submission,remove log system ready.

view log by role not started yet. Issue 's second part can start after discuss.

**Comment by hmert** [comment]
let's discuss. The user wants to see what happens on the journal, article, issue etc.. He/she needs to see  change log by each item.

**Comment by behramcelen** [comment]
ok, i get it. if  @aybarscengaver agree i can handle this issue.

**Comment by hmert** [comment]
just do it :)

**Comment by aybarscengaver** [comment]
@behramcelen  be careful about things like that 6b51d53abfad576e33ad94f92c192b67b0feddef

**Comment by behramcelen** [comment]
thanks for recheck. I inspected all commits about this issue.

**Comment by aybarscengaver** [comment]
:+1:

**Comment by behramcelen** [comment]
User Password change event can handle with Doctrine preUpdate listener but we can't do another log persist process it causes listener loop so error trace like below:
```
Error: Maximum function nesting level of '5000' reached, aborting! in /var/www/ojs/vendor/doctrine/common/lib/Doctrine/Common/Persistence/Event/LifecycleEventArgs.php line 85
```
My preUpdate listener code like below:
```php 
public function preUpdate(LifecycleEventArgs $args)
    {
        if (php_sapi_name()!='cli') {

            $entity = $args->getEntity();
            $entityManager = $args->getEntityManager();

            // perhaps you only want to act on some "User" entity
            if ($entity instanceof User) {

                if($args->hasChangedField('firstName')){
                    //log as eventlog
                    $event = new \Ojs\UserBundle\Entity\EventLog();
                    $event->setEventInfo(UserEventLogParams::$PASSWORD_CHANGE);
                    $event->setIp($this->container->get('request')->getClientIp());
                    $event->setUserId($entity->getId());
                    $entityManager->persist($event);

                    $entityManager->flush();
                }
            }
        }
    }
```
This problem mensioned there http://stackoverflow.com/q/16904462/2438520 but not answered with worked solution.

we can log like change password events on direct in update function. or have we got another solution? @hmert @aybarscengaver @hasantayyar

**Comment by hmert** [comment]
@behramcelen I see an accepted answer over there and seems good for me on the other hand we can log password changes on be half of update action.

Could you push your code about this issue and close if it was finished.

**Comment by behramcelen** [comment]
:ok_hand: i am handling now.

**Comment by behramcelen** [comment]
password change handling solved with user event subscriber. 87532c29dc2d7bab2069ed5093d89cdd55e9705e
