### ISSUE TITLE
Journal setup & configuration by wizard 

### ISSUE THREAD

**Issue by hmert** [okulbilisim/ojs#377]
- [x] Step 1
 1. Title
 2. Title abbr
 3. Subtitle
 4. Title transliterated
- [x] Step 2
 1. Issn
 2. Eissn
 3. First publish date
 4. Period
 5. Country
- [x] Step 3
 1. Submit Roles
 2. Languages
 3. Subjects
 4. Domain adress
- [x] Step 4 ( @aybarscengaver this fields may separated from the Journal Entity) 
 1. Mission
 2. Scope
 3. About
- [x] Step 5
 1. logo
 2. cover
 3. header
- [x] Step 6
 1.  theme

**Comment by hmert** [comment]
8b59ec46cf054f96aaf3dfc32575ced342f31235
279bbf7084ec88f8643b45d04f97f61f4a627578

**Comment by hmert** [comment]
mission scope and about texts may be added as dynamic pages.

**Comment by behramcelen** [comment]
good idea. we can use bootstrap wysiwyg editor (like http://summernote.org/) in journal setup wizard. So manager can write beautiful html about, mission texts. And than we can add only dynamic page links to Journal 's page.

**Comment by aybarscengaver** [comment]
but we don't want use wysiwyg editor in ojs. am i wrong @hmert ?

**Comment by hmert** [comment]
yup, only b,i,u and links are allowed on rich text editor areas.

**Comment by behramcelen** [comment]
Journal setup wizard can be reach from [BASE_URL]/manager/journal/setup/  or [BASE_URL]/manager/journal/{journal_id}/setup/
