### ISSUE TITLE
Meta tags

### ISSUE THREAD

**Issue by hasantayyar** [okulbilisim/ojs#404]

**Comment by aybarscengaver** [comment]
https://github.com/symfony-cmf/SeoBundle

**Comment by hasantayyar** [comment]
This is not all about seo.  There is some mandotary DC meta tags for academic works. 
Also I think symfony-cmf  bundles can be messy while adding to a symfony-standart project.

**Comment by aybarscengaver** [comment]
i missunderstood :)

**Comment by hasantayyar** [comment]
https://gist.github.com/hasantayyar/415063aed7138d23608e

http://dublincore.org/documents/2012/06/14/dcmi-terms/?v=elements#

**Comment by hasantayyar** [comment]
https://github.com/okulbilisim/ojs/commit/52e56635f188c9a35ec556a6d2aaa63f73e8084b
https://github.com/okulbilisim/ojs/commit/546d3a3317c4733abc32f2dd4beb04293c289890
https://github.com/okulbilisim/ojs/commit/49fd8613aaddf25f9202fc080fc7fad0d6bf2407
