### ISSUE TITLE
Workflow Manager

### ISSUE THREAD

**Issue by hmert** [okulbilisim/ojs#406]
Could you please have a look at it. :)

**Comment by behramcelen** [comment]
I can handle this

**Comment by hmert** [comment]
@behramcelen you cannot edit a step on workflow

**Comment by behramcelen** [comment]
@hmert you can edit from editor/workflow/step/{STEP_ID}/edit if you logged in as journal manager. if you are getting an error please can you notify me.

**Comment by behramcelen** [comment]
Did you do this https://github.com/okulbilisim/ojs/commit/17ac3689a77f5da25c696df790ff034ff6f876c9#comments? Because there are little changes on Mongodb Document and DataFixtures.

**Comment by hmert** [comment]
@behramcelen ok, I see. Could you please ROLE_SUPER_ADMIN can edit workflows. And let's give one boolen property, `public`. And you may close this issue :+1:

**Comment by hmert** [comment]
oh, stop :) Workflow are private for journals. Good job :clap:
