### ISSUE TITLE
Log System [ ElasticSearch + LogStash + Kibana ]

### ISSUE THREAD

**Issue by aybarscengaver** [okulbilisim/ojs#424]

**Comment by aybarscengaver** [comment]
https://www.digitalocean.com/community/tutorials/how-to-use-logstash-and-kibana-to-centralize-and-visualize-logs-on-ubuntu-14-04

**Comment by aybarscengaver** [comment]
https://www.ddreier.com/setting-up-elasticsearch-kibana-and-logstash/

**Comment by aybarscengaver** [comment]
http://thepracticalsysadmin.com/introduction-to-logstashelasticsearchkibana/

**Comment by hmert** [comment]
It's done by system administrators.
