### ISSUE TITLE
Date field Standardization 

### ISSUE THREAD

**Issue by hmert** [okulbilisim/ojs#455]

**Comment by aybarscengaver** [comment]
what is standart ? 

Atom (example: 2005-08-15T15:52:01+00:00)
HTTP Cookies (example: Monday, 15-Aug-2005 15:52:01 UTC)
ISO-8601 (example: 2005-08-15T15:52:01+0000)
RFC 850 (example: Monday, 15-Aug-05 15:52:01 UTC)

d-m-Y H:i:s ?
