### ISSUE TITLE
Journal Setup does not get current journal's settings (name, etc.)

### ISSUE THREAD

**Issue by hmert** [okulbilisim/ojs#470]
logined as demo_journal_manager and 
![screen shot 2015-04-16 at 11 01 56 am](https://cloud.githubusercontent.com/assets/182906/7176557/097cb05e-e428-11e4-908b-023b6a1d00ab.png)
clicked & redirected to http://ojs.io/manager/journal/setup/ 

Although my journal's has already name and other information, there is no value at setup secreen

**Comment by behramcelen** [comment]
7fc9bc7a9024fbd763064ecc09a1ec73257d11c6
4d0569ecf4b46ca79d3a3e5dc3fc05540e9db244
17b8cab08c20193cc4a8d5052fadbac6af15f9d5
This message will seem only for admins , if admin have unfinished journal (journal_status == false). Journal Setup link will redirect [BASE_LINK]/admin/journal/setup from there if admin have unfinished setup process then will resume setup process. if have not setup process, new setup process will be created and will resume from new created setup process.

**Comment by behramcelen** [comment]
journal manager can setup current journal from [BASE_URL]/manager/journal/setup
