### ISSUE TITLE
Deleted citation shown on Preview

### ISSUE THREAD

**Issue by beyzakokcan** [okulbilisim/ojs#483]

**Comment by aybarscengaver** [comment]
I can't repeat this bug. Are you sure is this a bug ? if it is, please say usage scenario, how did it before?

**Comment by beyzakokcan** [comment]
First I write the citations and save&continue then go back and delete them. I move on to preview and deleted citations are there.

**Comment by aybarscengaver** [comment]
It's is not a bug. It's usage problem. You must save changes with save&next button if remove one citation.

**Comment by beyzakokcan** [comment]
I saved it of course :)

**Comment by hmert** [comment]
It seems OK

![screen shot 2015-04-30 at 4 27 24 pm](https://cloud.githubusercontent.com/assets/182906/7413604/d1435d4e-ef55-11e4-8774-093df7ffb3b8.png)

**Comment by beyzakokcan** [comment]
I save&next 

![screen shot 2015-04-30 at 17 08 27](https://cloud.githubusercontent.com/assets/2804889/7414448/91e9a152-ef5b-11e4-8c1d-3e34a69aff2e.png)

still there

![screen shot 2015-04-30 at 17 08 01](https://cloud.githubusercontent.com/assets/2804889/7414451/95eabe6c-ef5b-11e4-8a3e-e3ee7f8be829.png)
