### ISSUE TITLE
Statistics

### ISSUE THREAD

**Issue by hmert** [okulbilisim/ojs#492]
- with google analytics?
- with mongo?

**Comment by hasantayyar** [comment]
We should add basic statistics for every article.
Detailed data may expire in 3 months but aggregated data should be permanent.

Statistics data should be stored on mongo.

Also we can add an extra parameter to paramters.yml to hold google analytics id.

**Comment by hmert** [comment]
Agreed and IMHO every journal may set it's own analytics id.

**Comment by hasantayyar** [comment]
added as new feature #504
