### ISSUE TITLE
user journal list role not affect the users' role

### ISSUE THREAD

**Issue by beyzakokcan** [okulbilisim/ojs#514]
I select the user from" user journal list" and assign roles but the user from the "users" tab, does not show that assigned roles. Or when I create a user from the "users " and assign a role; it is not listed on the journal user list. I understand we should match the user with a journal first but it gets complicated; if the roles from different pages do not affect each other.

**Comment by beyzakokcan** [comment]
Maybe;
Users can just create a new user and cannot assign a role but role of the user can be managed by the user journal roles to prevent the confusion.

**Comment by beyzakokcan** [comment]
This is not a question. It is a bug.

**Comment by hmert** [comment]
thanks to Beyza. I will open a new issue to define roles at user edit screen.
