### ISSUE TITLE
Journal alert

### ISSUE THREAD

**Issue by hmert** [okulbilisim/ojs#518]
![screen shot 2015-04-27 at 11 46 08 pm](https://cloud.githubusercontent.com/assets/182906/7357482/bd3a094e-ed37-11e4-9e38-2ee4be4107ff.png)

I'm not manager of this journal, however I can see setup alert and setup this journal

**Comment by behramcelen** [comment]
Its a normal issue, If admin have unfinished new journal setup progress.

**Comment by aybarscengaver** [comment]
i think, related #524

**Comment by hmert** [comment]
@behramcelen not normal. I'm not a journal admin, so there should not be a setup

@aybarscengaver agreed

**Comment by aybarscengaver** [comment]
@hmert admin setup like a new journal page.
