### ISSUE TITLE
Edit Journal User Page 404

### ISSUE THREAD

**Issue by beyzakokcan** [okulbilisim/ojs#527]
On the edit user page, If I leave empty "the user" and enter update; then the user becomes unavailable; page gives 404, if I go back and edit the user again.

**Comment by aybarscengaver** [comment]
Where is the user field on user edit page ?

**Comment by hmert** [comment]
I find another bug on this page. If I submit the form without any user selection, it throws following.
```
An exception occurred while executing 'INSERT INTO user_journal_role (user_id, journal_id, role_id) VALUES (?, ?, ?)' with params [null, 1, 3]:

SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'user_id' cannot be null 
```

**Comment by aybarscengaver** [comment]
oooops i get it.

30 Nisan 2015 Perşembe tarihinde, Hüseyin Mert <notifications@github.com>
yazdı:

> I find another bug on this page. If I submit the form without any user
> selection, it throws following.
>
> An exception occurred while executing 'INSERT INTO user_journal_role (user_id, journal_id, role_id) VALUES (?, ?, ?)' with params [null, 1, 3]:
>
> SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'user_id' cannot be null
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/okulbilisim/ojs/issues/527#issuecomment-97934863>.
>


-- 
*Aybars Cengaver*
*www.aybarscengaver.com <http://www.aybarscengaver.com>*
*Freelance Web Developer & Web Trainer*
