### ISSUE TITLE
Password should be more than 6 but not if admin gives it

### ISSUE THREAD

**Issue by beyzakokcan** [okulbilisim/ojs#528]
When the user wants to change his password, it gives warning that passw cannot be less than 6 letters. But admin has given it before; and it is less than 6 letters.

**Comment by aybarscengaver** [comment]
"admin" assert "superhero user". it has super powers. i can add password length limit for admin if you want.

**Comment by hmert** [comment]
please do not change current.

**Comment by beyzakokcan** [comment]
OK admin has super power but user CANNOT change the password. I wanted to say this makes a problem for the user not for the admin.

**Comment by beyzakokcan** [comment]
Admin is a human too. It should at least give a warning

**Comment by hmert** [comment]
@aybarscengaver I see the point. admin user may change password without rules but on password change page, all rules are present.

Please use all rules for everybody.
![screen shot 2015-04-30 at 4 09 35 pm](https://cloud.githubusercontent.com/assets/182906/7413343/7e0286e8-ef53-11e4-9c47-dd75e017310a.png)
