### ISSUE TITLE
Suggestion: Roles from "users" do not affect anything, so why exists?

### ISSUE THREAD

**Issue by beyzakokcan** [okulbilisim/ojs#529]
admin->Users page is just about creating the user and
admin->User journal roles is about the assigning roles and matching with the journals.

Also if I assign a role from the users page; it is no affect on anything as far as I know. So I think it can be removed from that page.

**Comment by beyzakokcan** [comment]
I do not need to assign a role..

![screen shot 2015-04-30 at 17 25 56](https://cloud.githubusercontent.com/assets/2804889/7414863/04c3be86-ef5e-11e4-9620-f1f0aa551936.png)

I can assign a role from there;

![screen shot 2015-04-30 at 17 26 11](https://cloud.githubusercontent.com/assets/2804889/7414871/186553fa-ef5e-11e4-98d3-57cb1694ee9f.png)

**Comment by aybarscengaver** [comment]
Role field on users pages for only system roles. But Journal Role Page is required for journal<->user relation .

**Comment by beyzakokcan** [comment]
But it does not affect anything. If I choose author from the users page for an user, what is going to happen?

**Comment by aybarscengaver** [comment]
I will hide this field, user form.

**Comment by aybarscengaver** [comment]
same as #514
