### ISSUE TITLE
Article Details

### ISSUE THREAD

**Issue by hmert** [okulbilisim/ojs#536]
Do we import all article's detail of information?

http://acta-medica-anatolia.ojs.io/ibuama/issue/6/22

http://journal.ojs.io/uluaricilik/issue/47/446

**Comment by aybarscengaver** [comment]
not yet.

**Comment by aybarscengaver** [comment]
- [ ] abstract
- [ ] affiliation
- [ ] biography
- [ ] cleanTitle
- [ ] competingInterests
- [ ] coverageChron
- [ ] coverageGeo
- [ ] coverageSample
- [ ] coverPageAltText
- [ ] discipline
- [ ] doiSuffix
- [ ] fileName
- [ ] height
- [ ] hideCoverPageAbstract
- [ ] hideCoverPageToc
- [ ] indexingState
- [ ] originalFileName
- [ ] projectID
- [ ] pub-id::doi
- [ ] pub-id::doi-is-valid
- [ ] pub-id::publisher-id
- [ ] showCoverPage
- [ ] sponsor
- [ ] subject
- [ ] subjectClass
- [ ] title
- [ ] type
- [ ] width


Article Setting fields.

**Comment by aybarscengaver** [comment]
affiliation field doesn't exist our system. some values for field:

```
1009004265	en_US	affiliation	Ondokuzmayis University, Medical Faculty	string
1009004280	en_US	affiliation	Ordu University	string
1009003078	en_US	affiliation	ORTA DOĞU TEKNİK ÜNİVERSİTESİ, EĞİTİM FAKÜLTESİ	string
1009003080	en_US	affiliation	ORTA DOĞU TEKNİK ÜNİVERSİTESİ, EĞİTİM FAKÜLTESİ	string
1009003093	en_US	affiliation	OSMANGAZİ ÜNİVERSİTESİ, EĞİTİM FAKÜLTES	string
1009004618	en_US	affiliation	Prof. Dr.	string
1009003652	en_US	affiliation	PROGRAM GELİŞTİRME SORUMLUSU, TERAKKİ VAKFI OKULLARI	string
1009004221	en_US	affiliation	Rize Üniversitesi Eğitim Fakültesi İlköğretim Bölümü	string
1009004251	en_US	affiliation	Rize University, Medical Faculty	string
1009004771	en_US	affiliation	Samsun Doğum evi	string
1009004218	en_US	affiliation	Sinop Üniversitesi	string
1009003096	en_US	affiliation	ÜMRANİYE TİCARET VE ANADOLU TİCARET MESLEK LİSESİ	string
1009003062	en_US	affiliation	ÜNYE ADNAN MENDERES TİCARET MESLEK LİSESİ	string
1009000295	en_US	affiliation	Uzman Dr	string
1009000298	en_US	affiliation	Uzman Dr	string
```

**Comment by aybarscengaver** [comment]
width field doesn't exists our system. field value integer on pkp.

**Comment by aybarscengaver** [comment]
pub-id::doi-is-valid field doesn't exists our system. some values :

5000071837		pub-id::doi-is-valid	10.12739/NWSA.2014.9.4.4C0189 	string
5000051150		pub-id::doi-is-valid	10.12748/uujms.201324253 	string
5000051151		pub-id::doi-is-valid	10.12748/uujms.201324254 	string
5000051154		pub-id::doi-is-valid	10.12748/uujms.201324257 	string
5000051155		pub-id::doi-is-valid	10.12748/uujms.201416495 	string
5000051156		pub-id::doi-is-valid	10.12748/uujms.201416496 	string
5000051159		pub-id::doi-is-valid	10.12748/uujms.201416499 	string
5000051161		pub-id::doi-is-valid	10.12748/uujms.201416501 	string
5000051162		pub-id::doi-is-valid	10.12748/uujms.201416502 	string
5000051166		pub-id::doi-is-valid	10.12748/uujms.201416505 	string
5000051167		pub-id::doi-is-valid	10.12748/uujms.201416506 	string
5000051143		pub-id::doi-is-valid	10.12748/uujms/20131708 	string
5000051144		pub-id::doi-is-valid	10.12748/uujms/20131709 	string
5000051147		pub-id::doi-is-valid	10.12748/uujms/20131712 	string
5000051148		pub-id::doi-is-valid	10.12748/uujms/20131713 	string
5000051149		pub-id::doi-is-valid	10.12748/uujms/20131714 	string
5000035996		pub-id::doi-is-valid	10.12780/UUSBD10	string

**Comment by aybarscengaver** [comment]
biography field not exists. values:

```
1009004639	tr_TR	biography	Ortaöğretim Matematik Eğitimi	string
1009004644	en_US	biography	pediatry/hematology and oncology	string
1009004652	en_US	biography	pediatry/hematology and oncology	string
1009004279	en_US	biography	Radiology Department	string
1009004308	tr_TR	biography	Sağlık Bilimleri Fakültesi Çocuk Gelişimi Bölümü	string
1009004317	tr_TR	biography	Sakarya Üniversitesi Eğitim Fakültesi İlköğretim Bölümü
↵                                                          Fen Bilgisi Eğitimi Anabilim Dalı
↵                                                          Muammer Sencer Caddesi
↵                                                          54300 Hendek/SAKARYA	string
1009004317	en_US	biography	Sakarya Universty
↵Education Faculty
↵Dept. of Primary Education	string
1009004542	en_US	biography	Sinop Üniveristesi Sağlık Yüksekokulu,
↵Çocuk Sağlığı ve hastalıkları Hemşireliği,	string
1009004755	en_US	biography	Students 
↵OMU Medical Faculty	string
1009004756	en_US	biography	Students 
↵OMU Medical Faculty	string
1009004734	en_US	biography	Suzan Duygu Erişti is an assistant professor at the Department of Computer Education and Instructional Technologies at Anadolu University, Turkey. She has an M.A and a Ph.D. on Fine Arts Education both focusing on computer assisted art education, design and instruction. She lists her research interests as technology assisted art education, multicultural art education, graphics design, interactive instruction and instructional design	string
1009004481	tr_TR	biography	Trainning	string
1009004319	tr_TR	biography	Uludağ Üniversitesi Eğitim Fakültesi İlköğretim Bölümü Araştırma Görevlisi.	string
1009004329	tr_TR	biography	Yard.Doç.Dr. Çocuk Cerrahisi A.B.D	string
```

**Comment by aybarscengaver** [comment]
showCoverPage field does not exists. values boolean.

**Comment by aybarscengaver** [comment]
cleanTitle field does not exists our system.

**Comment by aybarscengaver** [comment]
competingInterests does not exists.

**Comment by aybarscengaver** [comment]
coverageChron does not exists.

**Comment by aybarscengaver** [comment]
discipline field seems like subjects.

**Comment by aybarscengaver** [comment]
turned fileName field to header image.

**Comment by aybarscengaver** [comment]
unchecked fields not exists

**Comment by aybarscengaver** [comment]
i was checked againg and again and again.
