### ISSUE TITLE
5 step journal setup gives 404

### ISSUE THREAD

**Issue by beyzakokcan** [okulbilisim/ojs#549]
link: http://mersin-univ.ojs.io/manager/journal/setup/http://mersin-univ.ojs.io/ded

**Comment by aybarscengaver** [comment]
url is wrong. where is the link ?   give me some detail about usage scenario.

**Comment by beyzakokcan** [comment]
Yes url is wrong and it appears after I complete the setup.

**Comment by behramcelen** [comment]
fixed with https://github.com/okulbilisim/ojs/commit/0d6256c225c349113c154eb60d61f27a2b8f9734

**Comment by beyzakokcan** [comment]
Not pushed yet? Still I give 404.

**Comment by aybarscengaver** [comment]
i will check again

13 Mayıs 2015 Çarşamba tarihinde, beyzakokcan <notifications@github.com>
yazdı:

> Not pushed yet? Still I give 404.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/okulbilisim/ojs/issues/549#issuecomment-101690525>.
>


-- 
*Aybars Cengaver*
*www.aybarscengaver.com <http://www.aybarscengaver.com>*
*Freelance Web Developer & Web Trainer*
