### ISSUE TITLE
Critical: As assigning someone, search fails

### ISSUE THREAD

**Issue by beyzakokcan** [okulbilisim/ojs#551]
![screen shot 2015-05-06 at 11 00 54](https://cloud.githubusercontent.com/assets/2804889/7489443/4d05baca-f3df-11e4-9c6b-fb0a0844dec3.png)

**Comment by beyzakokcan** [comment]
I want to go on testing, if you quickly have a look at it.

**Comment by aybarscengaver** [comment]
give me full url plz.

**Comment by beyzakokcan** [comment]
http://mersin-univ.ojs.io/manager/workflow/article/assign/5549bec531998827108b4577

**Comment by aybarscengaver** [comment]
![ekran resmi 2015-05-06 11 19 39](https://cloud.githubusercontent.com/assets/803964/7489656/db76ce78-f3e1-11e4-9129-c291979ffcd8.png)

it works.

**Comment by aybarscengaver** [comment]
maybe  loading fail for one time.

**Comment by hmert** [comment]
but if there is no user with search term, it should throws an warning

**Comment by beyzakokcan** [comment]
I still get loading fail message :(

**Comment by beyzakokcan** [comment]
Editor cannot assign, but journal manager can.
