### ISSUE TITLE
Registration problem of the user assigned to an article

### ISSUE THREAD

**Issue by beyzakokcan** [okulbilisim/ojs#560]
If an editor sends an invitation to a user that is not in registered in the journal to review the article, the user sees the article invitation and accepts it but then the article is not reachable for that user.

**Comment by aybarscengaver** [comment]
how you can send invitation to unregistered user ? because i cant send an invitation to unregistered user on this screen.
![ekran resmi 2015-05-08 16 31 45](https://cloud.githubusercontent.com/assets/803964/7537230/c6d147d6-f59f-11e4-9499-4d74fda7eb99.png)
.

**Comment by beyzakokcan** [comment]
Registered to site but not to journal.

**Comment by ismailbaskin** [comment]
related #590

**Comment by hmert** [comment]
Anonymius login is removed. So this issue becomes meaningless.
