### ISSUE TITLE
Journal Import Details

### ISSUE THREAD

**Issue by aybarscengaver** [okulbilisim/ojs#579]
All fields must checked.

- [ ] abbreviation
- [*] acceptGiftSubscriptionPayments
- [*] acceptSubscriptionPayments
- [ ] additionalHomeContent
- [ ] additionalHomeContent_en
- [*] allowRegAuthor
- [*] allowRegReader
- [*] allowRegReviewer
- [ ] announcementsIntroduction
- [ ] articleAltLanguages
- [ ] articleEmailLog
- [ ] articleEventLog
- [ ] authorGuidelines
- [ ] authorGuidelines_en
- [ ] authorInformation
- [ ] authorInformationeng
- [ ] authorSelectsEditor
- [ ] authorSelfArchivePolicy
- [ ] boardEnabled
- [ ] categories
- [ ] competingInterestGuidelines
- [ ] contactAffiliation
- [x] contactEmail
- [x] contactFax
- [x] contactMailingAddress
- [x] contactName
- [x] contactPhone
- [x] contactTitle
- [ ] contributorNote
- [ ] contributors
- [ ] copyeditInstructions
- [ ] copyrightNotice
- [ ] copyrightNoticeAgree
- [ ] copySubmissionAckAddress
- [ ] copySubmissionAckAddress2
- [ ] copySubmissionAckAddress3
- [ ] copySubmissionAckPrimaryContact
- [ ] copySubmissionAckSpecified
- [ ] copySubmissionAckSpecified2
- [ ] copySubmissionAckSpecified3
- [ ] crossrefPassword
- [ ] crossrefUsername
- [ ] currency
- [ ] customAboutItems
- [ ] customHeaders
- [ ] defaultMetricType
- [ ] delayedOpenAccessDuration
- [ ] delayedOpenAccessPolicy
- [x] description
- [ ] disableUserReg
- [ ] displayCurrentIssue
- [ ] doiPrefix
- [ ] doiSuffix
- [ ] doiSuffixPattern
- [ ] donationFeeDescription
- [ ] donationFeeEnabled
- [ ] donationFeeName
- [ ] emailSignature
- [ ] enableAnnouncements
- [ ] enableAnnouncementsHomepage
- [*] enableAuthorSelfArchive
- [ ] enableComments
- [ ] enableDelayedOpenAccess
- [ ] enableLockss
- [ ] enableOpenAccessNotification
- [*] enablePageNumber
- [*] enablePublicArticleId
- [*] enablePublicGalleyId
- [*] enablePublicIssueId
- [*] enablePublicSuppFileId
- [*] enableSubscriptionExpiryReminderAfterMonths
- [*] enableSubscriptionExpiryReminderAfterWeeks
- [*] enableSubscriptionExpiryReminderBeforeMonths
- [*] enableSubscriptionExpiryReminderBeforeWeeks
- [*] enableSubscriptionOnlinePaymentNotificationPurchaseIndividual
- [*] enableSubscriptionOnlinePaymentNotificationPurchaseInstitutional
- [*] enableSubscriptionOnlinePaymentNotificationRenewIndividual
- [*] enableSubscriptionOnlinePaymentNotificationRenewInstitutional
- [*] envelopeSender
- [*] fastTrackFee
- [*] fastTrackFeeDescription
- [*] fastTrackFeeEnabled
- [*] fastTrackFeeName
- [*] focusScopeDesc
- [ ] header_image
- [ ] header_image_en
- [x] history
- [ ] historyDetails
- [ ] homeHeaderLogoImage
- [ ] homeHeaderLogoImageAltText
- [ ] homeHeaderTitle
- [ ] homeHeaderTitleAlt1
- [ ] homeHeaderTitleAlt2
- [ ] homeHeaderTitleImage
- [ ] homeHeaderTitleImageAltText
- [ ] homeHeaderTitleType
- [ ] homeHeaderTitleTypeAlt1
- [ ] homeHeaderTitleTypeAlt2
- [ ] homepageImage
- [ ] homepageImageAltText
- [ ] includeCreativeCommons
- [ ] initialNumber
- [ ] initials
- [ ] initialVolume
- [ ] initialYear
- [ ] isActiveOnOjs
- [ ] issuePerVolume
- [*] itemsPerPage
- [x] journalDescription
- [ ] journalFavicon
- [ ] journalPageFooter
- [ ] journalPageHeader
- [*] journalPaymentsEnabled
- [ ] journalStyleSheet
- [ ] journalTheme
- [ ] journalThumbnail
- [ ] journalThumbnailAltText
- [ ] journalTitleAltLanguages
- [ ] layoutInstructions
- [ ] librarianInformation
- [ ] lockssLicense
- [x] mailingAddress
- [ ] mailSubmissionsToReviewers
- [*] membershipFee
- [*] membershipFeeDescription
- [*] membershipFeeEnabled
- [*] membershipFeeName
- [ ] metaCitationOutputFilterId
- [ ] metaCitations
- [ ] metaCoverage
- [ ] metaCoverageChronExamples
- [ ] metaCoverageGeoExamples
- [ ] metaCoverageResearchSampleExamples
- [ ] metaDiscipline
- [ ] metaDisciplineExamples
- [ ] metaSubject
- [ ] metaSubjectClass
- [ ] metaSubjectClassTitle
- [ ] metaSubjectClassUrl
- [ ] metaSubjectExamples
- [ ] metaType
- [ ] metaTypeExamples
- [ ] navItems
- [ ] notifyAllAuthorsOnDecision
- [ ] numAnnouncementsHomepage
- [*] numDaysBeforeInviteReminder
- [*] numDaysBeforeSubmitReminder
- [*] numMonthsAfterSubscriptionExpiryReminder
- [*] numMonthsBeforeSubscriptionExpiryReminder
- [*] numPageLinks
- [*] numWeeksAfterSubscriptionExpiryReminder
- [*] numWeeksBeforeSubscriptionExpiryReminder
- [*] numWeeksPerReview
- [x] onlineIssn
- [ ] openAccessPolicy
- [ ] pageHeaderLogoImage
- [ ] pageHeaderLogoImageAltText
- [ ] pageHeaderTitle
- [ ] pageHeaderTitleAlt1
- [ ] pageHeaderTitleAlt2
- [ ] pageHeaderTitleImage
- [ ] pageHeaderTitleImageAltText
- [ ] pageHeaderTitleType
- [ ] pageHeaderTitleTypeAlt1
- [ ] pageHeaderTitleTypeAlt2
- [*] paymentMethodPluginName
- [x] primaryLocale
- [x] printIssn
- [ ] privacyStatement
- [ ] profileAltLanguages
- [ ] proofInstructions
- [ ] provideRefLinkInstructions
- [ ] pubFreqPolicy
- [*] publicationFee
- [*] publicationFeeDescription
- [*] publicationFeeEnabled
- [*] publicationFeeName
- [*] publicationFormatNumber
- [ ] publicationFormatTitle
- [ ] publicationFormatVolume
- [ ] publicationFormatYear
- [x] publisherInstitution
- [ ] publisherNote
- [ ] publisherType
- [x] publisherUrl
- [ ] publishingMode
- [*] purchaseArticleFee
- [*] purchaseArticleFeeDescription
- [*] purchaseArticleFeeEnabled
- [*] purchaseArticleFeeName
- [*] purchaseIssueFee
- [*] purchaseIssueFeeEnabled
- [*] rateReviewerOnQuality
- [ ] readerInformation
- [ ] readerInformationeng
- [*] refLinkInstructions
- [ ] remindForInvite
- [ ] remindForSubmit
- [*] requireAuthorCompetingInterests
- [*] requireReviewerCompetingInterests
- [*] restrictArticleAccess
- [*] restrictOnlyPdf
- [*] restrictReviewerFileAccess
- [*] restrictSiteAccess
- [*] reviewerAccessKeysEnabled
- [ ] reviewerDatabaseLinks
- [ ] reviewGuidelines
- [ ] reviewPolicy
- [ ] searchDescription
- [ ] searchKeywords
- [*] showEnsuringLink
- [*] showGalleyLinks
- [ ] sponsorNote
- [ ] sponsors
- [ ] templates
- [x] title
- [ ] volumePerYear
- [ ] waiverPolicy

**Comment by hmert** [comment]
- [ ] submissionChecklist
- [ ] submissionFee
- [ ] submissionFeeDescription
- [ ] submissionFeeEnabled
- [ ] submissionFeeName
- [ ] subscriptionAdditionalInformation
- [ ] subscriptionEmail
- [ ] subscriptionExpiryPartial
- [ ] subscriptionFax
- [ ] subscriptionMailingAddress
- [ ] subscriptionName
- [ ] subscriptionPhone
- [ ] useCopyeditors
- [ ] useEditorialBoard
- [ ] useLayoutEditors
- [ ] useProofreaders
- [ ] supportedFormLocales
- [ ] supportedLocales
- [ ] supportedSubmissionLocales
- [ ] supportEmail
- [ ] supportName
- [ ] supportPhone
