### ISSUE TITLE
Journal Settings give error 

### ISSUE THREAD

**Issue by beyzakokcan** [okulbilisim/ojs#581]
http://ojs.io/manager/journal/settings/submission  

I logged in as demo_journal_manager of "Science Material journal" and as I was setting the article submission settings etc., I got this error;

Error: Call to a member function hasRole() on a non-object

**Comment by hmert** [comment]
the problem is settings page role checking.

**Comment by aybarscengaver** [comment]
but it seems like ok ? 
login with demo_journal_manager user
go to http://ojs.io/manager/journal/settings page
and everythink ok.

**Comment by aybarscengaver** [comment]
ok, i see now.
