### ISSUE TITLE
ACL Permission integration.

### ISSUE THREAD

**Issue by aybarscengaver** [okulbilisim/ojs#590]
http://symfony.com/doc/current/cookbook/security/acl.html

**Comment by aybarscengaver** [comment]
ACL only usable for things like article comments. 
JournalManager, Editor permission is complex more than. 

SuperAdmin must have all privileges.
JournalManager only must have own journal, articles of own journal, issues of own journal and other own journal privileges.
Author must have own article edit, submission privileges. 
Editor must have privileges on #588 
Reviewer must have review access allowed articles by editor or journal manager. 
Subscription Manager only must have privileges about journal subscriptions.
Section Editor ?
Layout Editor ?
Copyeditor ? 
Proofreader ?
Reader only is a reader.

ping @hmert @hasantayyar

**Comment by ismailbaskin** [comment]
https://github.com/Problematic/ProblematicAclManagerBundle

**Comment by ismailbaskin** [comment]
Adding ACE record
```
$article = $this->getDoctrine()->getRepository('OjsJournalBundle:Article')->find(99);
$journalId = 1;
$journalRole = 'Author’;
$id = new JournalRoleSecurityIdentity(journalId, $journalRole); // OR USER $id = $this->getUser();

$this->get('problematic.acl_manager')->on($article)->to($id)->permit(MaskBuilder::MASK_OWNER)->save();
```
Checking permissions
```
if($this->isGranted('EDIT', $article)) {
   throw new \Exception();
}
```

**Comment by ismailbaskin** [comment]
5d85c72f0b0b6ac489b80bff33042f9d5163e935
