### ISSUE TITLE
Entities delete action CSRF protection

### ISSUE THREAD

**Issue by behramcelen** [okulbilisim/ojs#609]
For prevent CSRF we can use tokens in every delete action.

Related links:
-https://www.digitalocean.com/community/tutorials/how-to-use-symfony2-to-perform-crud-operations-on-a-vps-part-2
-http://alexandre-salome.fr/blog/Secure-Actions-Symfony2
-http://labs.octivi.com/symfony2-cross-site-request-forgery-protection-for-controller-actions/

**Comment by ismailbaskin** [comment]
SF form is very useful for CSRF protection and HTTP method override. Delete actions must be run with http delete method.
