### ISSUE TITLE
Mailtype entity needs grid list

### ISSUE THREAD

**Issue by aybarscengaver** [okulbilisim/ojs#631]

**Comment by behramcelen** [comment]
I guess we are not using this controller anywhere. Can be look from https://github.com/okulbilisim/ojs/search?utf8=%E2%9C%93&q=MailType and https://github.com/okulbilisim/ojs/blob/75c077e6058e7b54ef8620211fa8914634836071/src/Ojs/JournalBundle/Controller/MailTypeController.php#L7 this entity doesn 't exist also.

**Comment by behramcelen** [comment]
Ojs not using this MailTypeController anywhere.So we will remove this. I guess this controller equels to OjsJournalBundle:MailTemplate controller.
