### ISSUE TITLE
People directory

### ISSUE THREAD

**Issue by utkuaydin** [okulbilisim/ojs#651]
Using the people directory (which would live at `/people`), users of the system would be able to see a list of everyone who are affiliated with a journal (author, editor, manager etc.)

* Each user's contributions to any journal would be very easy to spot
* Statistics of each user could be displayed (articles written, issues editored etc.)
* This list could be filtered using journals, institutions or areas of expertise

**Comment by hmert** [comment]
I expect `/journals` page design with people oriented not a grid :)
