### ISSUE TITLE
Password fields

### ISSUE THREAD

**Issue by aybarscengaver** [okulbilisim/ojs#653]
AUTOCOMPLETE attribute is not disabled in HTML FORM/INPUT element containing password type input.  Passwords may be stored in browsers and retrieved.

**Comment by aybarscengaver** [comment]
Solution
Turn off AUTOCOMPLETE attribute in form or individual input elements containing password by using AUTOCOMPLETE='OFF'

**Comment by hmert** [comment]
it's already enabled with browsers
