### ISSUE TITLE
All update forms must use "put" as method.

### ISSUE THREAD

**Issue by aybarscengaver** [okulbilisim/ojs#660]
Related links;
- http://symfony.com/doc/current/book/forms.html#changing-the-action-and-method-of-a-form
- http://symfony.com/doc/current/cookbook/routing/method_parameters.html

**Comment by ismailbaskin** [comment]
Also all delete actions must use "delete"

**Comment by hmert** [comment]
http://ojs.io/admin/institution/5/delete not working with admin user
