### ISSUE TITLE
globally integration of tag system

### ISSUE THREAD

**Issue by hmert** [okulbilisim/ojs#665]
all tags should be
- [x] indexed by elastic
- [x] tags cloud page
- [x] refactor all input fields for 

#335

**Comment by hmert** [comment]
#335 related

**Comment by behramcelen** [comment]
Tag search page -> http://ojs.io/tag/{tag}
Tag Cloud -> http://ojs.io/tags/cloud
For use tag autocomplete inputs use `fos:elastic:populate` & `bower update`
