### ISSUE TITLE
IssueManagerController & IssueController must be merged

### ISSUE THREAD

**Issue by ismailbaskin** [okulbilisim/ojs#679]

**Comment by ismailbaskin** [comment]
http://ojs.io/manager/issues
` Class "Ojs\ManagerBundle\Controller\IssueManagerController" does not exist. `

**Comment by behramcelen** [comment]
there is no link like http://ojs.io/manager/issues it must be http://ojs.io/manager/issue. link is placed in dashboard page and now runs correctly.
