### ISSUE TITLE
isJournalManager function not exists

### ISSUE THREAD

**Issue by behramcelen** [okulbilisim/ojs#688]
- [x] [2015-06-02 01:51:59] assetic.ERROR: The template "OjsWorkflowBundle:Manager:previewWorkingStep.html.twig" contains an error: The function "isJournalManager" does not exist in "OjsWorkflowBundle:Manager:previewWorkingStep.html.twig" at line 87
- [x] [2015-06-02 01:51:59] assetic.ERROR: The template "OjsWorkflowBundle:Manager:invitationPreview.html.twig" contains an error: The function "isJournalManager" does not exist in "OjsWorkflowBundle:Manager:invitationPreview.html.twig" at line 84  
- [x] [2015-06-02 01:51:59] assetic.ERROR: The template "OjsWorkflowBundle:Manager:articles.html.twig" contains an error: The function "isJournalManager" does not exist in "OjsWorkflowBundle:Manager:articles.html.twig" at line 62  
- [x] [2015-06-02 01:51:59] assetic.ERROR: The template "OjsWorkflowBundle:Manager:article.html.twig" contains an error: The function "isJournalManager" does not exist in "OjsWorkflowBundle:Manager:article.html.twig" at line 31  
- [x] [2015-06-02 01:51:59] assetic.ERROR: The template "OjsWorkflowBundle:ReviewForm:index.html.twig" contains an error: The function "isJournalManager" does not exist in "OjsWorkflowBundle:ReviewForm:index.html.twig" at line 38  
- [x] [2015-06-02 01:51:59] assetic.ERROR: The template "OjsWorkflowBundle:WorkflowStep/Template:templates.html.twig" contains an error: The function "isJournalManager" does not exist in "OjsWorkflowBundle:WorkflowStep/Template:templates.html.twig" at line 47  
- [x] [2015-06-02 01:52:00] assetic.ERROR: The template "OjsWorkflowBundle:WorkflowStep/Template:show_step.html.twig" contains an error: The function "isJournalManager" does not exist in "OjsWorkflowBundle:WorkflowStep/Template:show_step.html.twig" at line 114  
- [x] [2015-06-02 01:52:00] assetic.ERROR: The template "OjsWorkflowBundle:WorkflowStep/Template:template.html.twig" contains an error: The function "isJournalManager" does not exist in "OjsWorkflowBundle:WorkflowStep/Template:template.html.twig" at line 56  
- [x] [2015-06-02 01:52:00] assetic.ERROR: The template "OjsWorkflowBundle:WorkflowStep:show.html.twig" contains an error: The function "isJournalManager" does not exist in "OjsWorkflowBundle:WorkflowStep:show.html.twig" at line 122  
[2015-06-02 01:52:00] assetic.ERROR: The template "OjsWorkflowBundle:WorkflowStep:index.html.twig" contains an error: The function "isJournalManager" does not exist in "OjsWorkflowBundle:WorkflowStep:index.html.twig" at line 57  
- [x] [2015-06-02 01:52:00] assetic.ERROR: The template "OjsWorkflowBundle:ReviewFormItem:index.html.twig" contains an error: The function "isJournalManager" does not exist in "OjsWorkflowBundle:ReviewFormItem:index.html.twig" at line 37  
[2015-06-02 01:52:02] assetic.ERROR: The template "OjsJournalBundle:JournalContact:new.html.twig" contains an error: The function "isJournalManager" does not exist in "OjsJournalBundle:JournalContact:new.html.twig" at line 33  
- [x] [2015-06-02 01:52:11] assetic.ERROR: The template "OjsSiteBundle:Journal:journal_right_block.html.twig" contains an error: The function "isJournalManager" does not exist in "OjsSiteBundle:Journal:journal_right_block.html.twig" at line 1

**Comment by ismailbaskin** [comment]
intentionally removed. Please fix with appropriate ACL check.

**Comment by ismailbaskin** [comment]
related #697

**Comment by utkuaydin** [comment]
`http://ojs.dev/editor/workflow` also has this problem

**Comment by hmert** [comment]
@ismailbaskin you should review this commit
