### ISSUE TITLE
Journal and institution application validation

### ISSUE THREAD

**Issue by utkuaydin** [okulbilisim/ojs#708]
Application forms for both journals and institutions need proper validation. None exists currently.

Related URLs: 
- [ ] `http://ojs.dev/apply/journal`
- [x] `http://ojs.dev/apply/institution`

**Comment by ismailbaskin** [comment]
c6080d34e1699c54f530675e5c40b44af87e855b

**Comment by ismailbaskin** [comment]
https://github.com/okulbilisim/ojs/commit/7c83cdd
