### ISSUE TITLE
Fix problematic delete actions in admin panel

### ISSUE THREAD

**Issue by utkuaydin** [okulbilisim/ojs#727]
Since nearly all of the delete URLs only accept requests with `DELETE` method, most of the deletion actions in admin panel don't work (especially the generated grid actions).

**Comment by behramcelen** [comment]
Problems reason is not Method use. not edited route names causes this problem.

**Comment by utkuaydin** [comment]
@behramcelen: 3666e3d292eb8263fdf4585843a23397703af6b3 doesn't help.

**Comment by behramcelen** [comment]
https://github.com/okulbilisim/ojs/issues/727#issuecomment-112756709 closes issue.
