### ISSUE TITLE
OAI Pagination Bug

### ISSUE THREAD

**Issue by hmert** [okulbilisim/ojs#746]
OAI pagination is not developed

**Comment by aybarscengaver** [comment]
its resumptionToken.

**Comment by aybarscengaver** [comment]
Thats like http://ojs.io/api/oai/?verb=ListRecords&resumptionToken=db9ba90ceb097984a83819ff7646af2d

**Comment by hmert** [comment]
Do we have more than 100 records at any journal?

**Comment by aybarscengaver** [comment]
Yes http://ojs.io/api/oai/?verb=ListRecords&metadataPrefix=oai_dc&set=yyutbd-1
