### ISSUE TITLE
Reports

### ISSUE THREAD

**Issue by hmert** [okulbilisim/ojs#791]
- [x] reports page redesign
- [x] use only http://c3js.org/
- [ ] remove google analytics
- [x] Article download counts
- [x] Article view counts
- [x] New user graphic
- [x] Total user count
- [x] User titles graphic
- [x] User gender graphic
- [x] Article languages graphic
- [x] New articles graphic

**Comment by aybarscengaver** [comment]
related https://github.com/okulbilisim/ojs/commit/c301594
