### ISSUE TITLE
Subjects & Featured Sections are Broken?

### ISSUE THREAD

**Issue by hmert** [okulbilisim/ojs#810]
![image](https://cloud.githubusercontent.com/assets/182906/8766954/7eb1daae-2e54-11e5-85c9-ce847ef1132f.png)

**Comment by aybarscengaver** [comment]
Featured section has not content. its staticaly.

**Comment by hmert** [comment]
Really? What about subjects?

**Comment by aybarscengaver** [comment]
its fixed

20 Temmuz 2015 Pazartesi tarihinde, Hüseyin Mert <notifications@github.com>
yazdı:

> Really? What about subjects?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/okulbilisim/ojs/issues/810#issuecomment-122862120>.
>


-- 
*Aybars Cengaver*
*www.aybarscengaver.com <http://www.aybarscengaver.com>*
*Freelance Web Developer & Web Trainer*
