### ISSUE TITLE
API Refactor

### ISSUE THREAD

**Issue by hmert** [okulbilisim/ojs#844]
- [ ] Requests with ACL
- [x] Check correct responses
- [x] All features with REST API

**Comment by behramcelen** [comment]
Referances:
https://github.com/liuggio/symfony2-rest-api-the-best-2013-way
http://welcometothebundle.com/symfony2-rest-api-the-best-2013-way/
http://welcometothebundle.com/web-api-rest-with-symfony2-the-best-way-the-post-method/
http://welcometothebundle.com/symfony2-rest-api-the-best-way-part-3/
thanks a lot @liuggio :clap:
