### ISSUE TITLE
Twig method "stat" causes a problem

### ISSUE THREAD

**Issue by utkuaydin** [okulbilisim/ojs#862]
Commented lines [here](https://github.com/okulbilisim/ojs/blob/bedf3ea7212eca18a4780eb5a1000de2f48dc2d2/src/Ojs/SiteBundle/Resources/views/Article/article_page.html.twig#L49-L50) causes this problem: `Attempted to call an undefined method named "getViewStat" of class "Ojs\ReportBundle\Twig\AnalyticsExtension"`

**Comment by hmert** [comment]
#841

**Comment by utkuaydin** [comment]
#884 took care of this problem.
