### ISSUE TITLE
Save the initial data using ORM

### ISSUE THREAD

**Issue by utkuaydin** [okulbilisim/ojs#864]
At the moment, `ojs:install:initial-data` command uses Alice fixtures to save the initial data. But Alice's purpose is to populate the database with fake data, so the initial data should be saved using ORM.

- [x] Publisher
- [x] Journal
- [x] User
- [ ] Issue (+file)
- [x] Section
- [ ] Article (+file,citation)
- [x] Page
- [x] Post
- [x] Announcement

**Comment by hmert** [comment]
:+1:
