### ISSUE TITLE
Ojs\JournalBundle\Entity\Citation::$currentLocale was never imported

### ISSUE THREAD

**Issue by hmert** [okulbilisim/ojs#904]
[Semantical Error] The annotation "Prezent\CurrentLocale" in property Ojs\JournalBundle\Entity\Citation::$currentLocale was never imported. Did you maybe forget to add a "use" statement for this annotation? 

http://ojs.io/journal/1/article/1/citation/

**Comment by behramcelen** [comment]
https://github.com/okulbilisim/ojs/commit/a4e313ebb9fb59880674bb04848c8e3bdb09cebd closes this issue.
