### ISSUE TITLE
Cannot move on "Article Submission"

### ISSUE THREAD

**Issue by beyzakokcan** [okulbilisim/ojs#915]
I filled second step of article submission form and clicked on "save", but it stays there and I cannot move on to third step.

**Comment by hmert** [comment]
have you fil all values?

**Comment by beyzakokcan** [comment]
no. But you said it is not important because it can be a draft and author can continue then.

**Comment by beyzakokcan** [comment]
Also it should show the mandatory fields.

**Comment by hmert** [comment]
14fdf305fd7d6377f4a60e8d2b5a380476601515

**Comment by utkuaydin** [comment]
It isn't fixed yet!

**Comment by beyzakokcan** [comment]
the page says "This value should not be blank." but it does not show the blank fields and I actually filled all the fields.

**Comment by utkuaydin** [comment]
@beyzakokcan Commit 52f8b6e solves the unfriendly validation messages problem that you mentioned. @behramcelen will take care of the mandatory languge tab problem. Also, saving as a draft feature has its own issue now, so you can follow its implementation process [here](https://github.com/okulbilisim/ojs/issues/932).

**Comment by behramcelen** [comment]
@utkuaydin @beyzakokcan inline form error output issue will be solved in https://github.com/okulbilisim/ojs/issues/938
