### ISSUE TITLE
Register validation problem

### ISSUE THREAD

**Issue by hmert** [okulbilisim/ojs#916]

**Comment by zaferkanbur** [comment]
It seem OK when I registered myself. But I can't log in the system when I input the my credentials. It says   "User account is disabled." I guess this happens because of that activation mail isn't sent. Can you check it out?

**Comment by hmert** [comment]
Google has been disabled our mailing port, so we will change our mail provider few hours.

**Comment by zaferkanbur** [comment]
ok then.

2015-08-25 14:55 GMT+03:00 Hüseyin Mert <notifications@github.com>:

**Comment by hmert** [comment]
user do not need to confirm his/her email.
