### ISSUE TITLE
cannot upload a file on article submission

### ISSUE THREAD

**Issue by beyzakokcan** [okulbilisim/ojs#937]
I cannot upload a file in the first step of the article submission.

**Comment by hmert** [comment]
could you be more specific about which step? 
![image](https://cloud.githubusercontent.com/assets/182906/9515798/79c09294-4cac-11e5-89e7-7a6cc49e2e56.png)

BTW, I could uploaded a file.

**Comment by beyzakokcan** [comment]
Yes this step. I logged in as beyza, dergipark

**Comment by beyzakokcan** [comment]
I first did not upload any file and said save&next. Then next page did not open and I tried to upload a file then.

**Comment by hmert** [comment]
![image](https://cloud.githubusercontent.com/assets/182906/9516649/b89a5800-4cb2-11e5-8794-e07ae83fd2af.png)

the problem is about #933 and which users has api key.
