### ISSUE TITLE
Journal period should also contain the months

### ISSUE THREAD

**Issue by beyzakokcan** [okulbilisim/ojs#960]
http://ojs.io/journal/3/settings/
For example;
Journal has a period of 3. Then it should say June, July, August or Summer as well. This is important. There is a criteria for this.

**Comment by beyzakokcan** [comment]
This is the criteria in Turkish

Ay bazında yayınlanan dergilerin yayın sıklığına ilişkin ifadeler  
Aylık: Monthly
2 Aylık: Bimonthly
3 Aylık: Quarterly
4 Aylık: Triquarterly
6 Aylık: Biannualy
Yıllık: Annualy
 
Mevsim bazında yayınlan dergilerin yayın sıklığına ilişkin ifadeler  
İlkbahar: Spring
Yaz: Summer
Sonbahar: Fall 
Kış: Winter

**Comment by hmert** [comment]
- [ ] Published frequency (only text) on explore page

**Comment by hmert** [comment]
- [ ] Only Admin's can CRUD periods.
- [ ] JM can select multi periods on period field
