### ISSUE TITLE
Copy Right text BUG

### ISSUE THREAD

**Issue by beyzakokcan** [okulbilisim/ojs#970]
![screen shot 2015-08-28 at 17 18 00](https://cloud.githubusercontent.com/assets/2804889/9548347/c639bb4e-4da8-11e5-9790-6dde85691b94.png)
 When I click on the "from here", it gives an error. 
And there is no statement about the copyright which I entered on the settings page

**Comment by hmert** [comment]
![image](https://cloud.githubusercontent.com/assets/182906/9564477/6e730758-4eb1-11e5-9ee0-c34171084ea6.png)
fixed
