### ISSUE TITLE
Editor cannot edit the metadata of the article

### ISSUE THREAD

**Issue by beyzakokcan** [okulbilisim/ojs#981]
Editor cannot see the TR version of the metadata and more importantly cannot edit the metadata. Thread is opened.

http://ojs.io/journal/3/articles/15

**Comment by beyzakokcan** [comment]
Editor can view TR version if he changes the page language. But it is a different case, I think. No matter what page language is, he should see what author filled

**Comment by behramcelen** [comment]
Depends https://github.com/okulbilisim/ojs/issues/990

**Comment by behramcelen** [comment]
fixed with workflow-bundle
