### ISSUE TITLE
Editor vs Journal Manager Roles

### ISSUE THREAD

**Issue by hmert** [okulbilisim/ojs#993]
Editor focussed on content.

Only Journal Manager can do:

- [x] Settings
- [x] Workflow steps
- [x] Contacts
- [x] Design
- [x] Theme
- [x] Board

**Comment by behramcelen** [comment]
closes with https://github.com/okulbilisim/ojs/commit/915eff7ad7e63d9bb02cb2a569fd380c62b8de6f
